"""add simulation sessions and turns

Revision ID: e4523b90428d
Revises: da2c8ac93ad3
Create Date: 2026-09-05 11:24:04.886301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4523b90428d'
down_revision: Union[str, None] = 'da2c8ac93ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('rep_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', name='session_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_sessions_org_id'), 'simulation_sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_simulation_sessions_rep_id'), 'simulation_sessions', ['rep_id'], unique=False)
    op.create_index(op.f('ix_simulation_sessions_scenario_id'), 'simulation_sessions', ['scenario_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('rep', 'ai_customer', name='speaker'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['simulation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_simulation_sessions_scenario_id'), table_name='simulation_sessions')
    op.drop_index(op.f('ix_simulation_sessions_rep_id'), table_name='simulation_sessions')
    op.drop_index(op.f('ix_simulation_sessions_org_id'), table_name='simulation_sessions')
    op.drop_table('simulation_sessions')
    # ### end Alembic commands ###
